spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newsDB?useUnicode=true&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop


